### ISSUE TITLE
Fix issue in http_headers

### ISSUE THREAD

**Issue by inetshell** [HobOps/helm-chart-helper#12]
```
Fix "http_headers":
      readinessProbe:
        failureThreshold: 3
        httpGet:
          http_headers:
          - name: Host
            value: example.com
```
